# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_top_bar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.widget_top_bar.sizePolicy().hasHeightForWidth())
        self.widget_top_bar.setSizePolicy(sizePolicy)
        self.widget_top_bar.setObjectName("widget_top_bar")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_top_bar)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget_top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radio_age = QtWidgets.QCheckBox(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.radio_age.setFont(font)
        self.radio_age.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radio_age.setObjectName("radio_age")
        self.gridLayout_6.addWidget(self.radio_age, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 3, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.combo_patterns = QtWidgets.QComboBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_patterns.sizePolicy().hasHeightForWidth())
        self.combo_patterns.setSizePolicy(sizePolicy)
        self.combo_patterns.setMinimumSize(QtCore.QSize(0, 30))
        self.combo_patterns.setObjectName("combo_patterns")
        self.gridLayout_7.addWidget(self.combo_patterns, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.widget_5.setFont(font)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout.addWidget(self.widget_5, 0, 2, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget_top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.button_save = QtWidgets.QPushButton(self.widget_6)
        self.button_save.setMinimumSize(QtCore.QSize(0, 30))
        self.button_save.setObjectName("button_save")
        self.gridLayout_9.addWidget(self.button_save, 0, 0, 1, 1)
        self.button_load = QtWidgets.QPushButton(self.widget_6)
        self.button_load.setMinimumSize(QtCore.QSize(0, 30))
        self.button_load.setObjectName("button_load")
        self.gridLayout_9.addWidget(self.button_load, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_6, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget_top_bar, 0, 0, 1, 1)
        self.frame_grid = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(self.frame_grid.sizePolicy().hasHeightForWidth())
        self.frame_grid.setSizePolicy(sizePolicy)
        self.frame_grid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grid.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_grid.setObjectName("frame_grid")
        self.main_grid_layout = QtWidgets.QGridLayout(self.frame_grid)
        self.main_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.main_grid_layout.setObjectName("main_grid_layout")
        self.gridLayout_2.addWidget(self.frame_grid, 1, 0, 1, 1)
        self.widget_bottom_bar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.widget_bottom_bar.sizePolicy().hasHeightForWidth())
        self.widget_bottom_bar.setSizePolicy(sizePolicy)
        self.widget_bottom_bar.setObjectName("widget_bottom_bar")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_bottom_bar)
        self.gridLayout_5.setContentsMargins(12, -1, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_7 = QtWidgets.QWidget(self.widget_bottom_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_5.addWidget(self.widget_7, 0, 1, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget_bottom_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.button_play = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_play.sizePolicy().hasHeightForWidth())
        self.button_play.setSizePolicy(sizePolicy)
        self.button_play.setMinimumSize(QtCore.QSize(0, 30))
        self.button_play.setObjectName("button_play")
        self.gridLayout_10.addWidget(self.button_play, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_8, 0, 2, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget_bottom_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.button_clear = QtWidgets.QPushButton(self.widget_4)
        self.button_clear.setMinimumSize(QtCore.QSize(0, 30))
        self.button_clear.setObjectName("button_clear")
        self.gridLayout_8.addWidget(self.button_clear, 0, 0, 1, 1)
        self.button_single_step = QtWidgets.QPushButton(self.widget_4)
        self.button_single_step.setMinimumSize(QtCore.QSize(0, 30))
        self.button_single_step.setObjectName("button_single_step")
        self.gridLayout_8.addWidget(self.button_single_step, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_bottom_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.slider_speed = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(75)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_speed.sizePolicy().hasHeightForWidth())
        self.slider_speed.setSizePolicy(sizePolicy)
        self.slider_speed.setMinimum(1)
        self.slider_speed.setMaximum(60)
        self.slider_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_speed.setObjectName("slider_speed")
        self.gridLayout_4.addWidget(self.slider_speed, 1, 1, 1, 1)
        self.label_fps = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fps.sizePolicy().hasHeightForWidth())
        self.label_fps.setSizePolicy(sizePolicy)
        self.label_fps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fps.setObjectName("label_fps")
        self.gridLayout_4.addWidget(self.label_fps, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 0, 4, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.widget_bottom_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_5.addWidget(self.widget_9, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget_bottom_bar, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Conway\'s Game Of Life"))
        self.radio_age.setText(_translate("MainWindow", "Show Cell Age"))
        self.label_3.setText(_translate("MainWindow", "Pattern:"))
        self.button_save.setText(_translate("MainWindow", "Save"))
        self.button_load.setText(_translate("MainWindow", "Load"))
        self.button_play.setText(_translate("MainWindow", "Play"))
        self.button_clear.setText(_translate("MainWindow", "Clear"))
        self.button_single_step.setText(_translate("MainWindow", "Single Step"))
        self.label_fps.setText(_translate("MainWindow", "- FPS"))
        self.label.setText(_translate("MainWindow", "Speed"))

